- name: ping the server
  hosts: web  #ping module fails to local host, it msut be other server
  #connection: local
  tasks:
    - name: ping the server
      ansible.builtin.ping:
        # msg: "ping the server"
        